### PR TITLE
welcome to minorities on home page

### PR DESCRIPTION
**Pull request by sofer**
As suggested in https://github.com/foundersandcoders/business/issues/52

### CODE REVIEW

**Comment by sofer** [comment]
@iteles?

**Comment by sofer** [comment]
the new copy reads, "We particularly welcome applications from women and members of minority groups". It appears just below the APPLY button and is only visible on larger screens (it looks a bit crap on a mobile device). It's really just a placeholder until we can come up with a better way of reaching out, but it puts a pretty clear marker in the sand, as suggested here https://github.com/foundersandcoders/business/issues/52.

**Comment by iteles** [comment]
Yea, I'm still not so sure about this. It would really make me roll my eyes if I saw this on a website, whether I was a man or woman. Can we do some A/B testing on this?
I don't know how harp deals with google content experiments but might work?

**Comment by sofer** [comment]
@iteles I trust your judgement. Closing now.

**Comment by iteles** [comment]
Well I still feel this is the perfect candidate for a/b testing! Do we have someone 'in charge' of the website?

**Comment by sofer** [comment]
@iteles we don't have any one person with responsibility for the website. Also, with only 200 or so sessions and 2-3 Part 1 applications per day, I suspect we might find it tricky to tease useful results out of an A/B test in this case.

**Comment by iteles** [comment]
I imagine the responsibility for the site will come out of the new comms groups. Is there an issue for that? It seems to be taking a while to settle!

**Comment by iteles** [comment]
Also, I might use this PR to do some user testing at the next ladies of code if it's appropriate.

**Comment by oturnermajor** [comment]
@iteles this seems like quite a legit tactic (see [here](https://www.citizensadvice.org.uk/about-us/how-citizens-advice-works/job-and-voluntary-opportunities/citizens-advice-job-opportunities/) and [here](http://www.ucl.ac.uk/hr/docs/recruit_positive.php)) and it was the most popular suggestion on the thread from https://github.com/foundersandcoders/business/issues/52. 

Would it help if we thought more about where we placed it and/or qualify it more with some background about why it's important etc? Or would it trigger an eye-roll regardless no matter what?

**Comment by iteles** [comment]
@oturnermajor All fair points - I still think user testing is the way to go with this!

What triggers the eye roll is the wording I think.
>Citizens Advice recognises the positive value of diversity, promotes equality and challenges discrimination. We welcome and encourage job applications from people of all backgrounds.

is a more qualified statement than "We particularly welcome female applicants and those from an ethnic minority"

We've already been accused of favouring female applicants so we just need to provide a bit more context as per your examples. Suggestions welcome!

**Pull request closed without merging**
