### PR TITLE
may/june course dates

### PR DESCRIPTION
**Pull request by rub1e**
@sofer please approve, then @rug1 please merge when dan's approved

### CODE REVIEW

**Comment by sofer** [comment]
@rug1 approved.

**Comment by sofer** [comment]
@rug1 updated and ready to merge. Let me know if you want a hand.

**Comment by iteles** [comment]
Merging this one in given the time sensitivity and the other PRs open for review.

**Comment by rub1e** [comment]
Yeah it's the compiling as well as the merging that we need. I'll ask ruth to carve out some time first thing

**Pull request merged**
