### PR TITLE
2016 application dates

### PR DESCRIPTION
**Pull request by sofer**

### CODE REVIEW

**Comment by Jbarget** [comment]
@sofer 

line 3:
It says FAC8 will start on May 18th is a wednesday, do you mean 16th May (17 weeks from the start of FAC7) or potentially 9th May (16 weeks from the start of FAC7)

https://github.com/foundersandcoders/oursite/pull/197/files#diff-b0e9bdf75d0c4dbda2734cbac51546eaR3

lines 29 - 31:
ask similar things of the candidates, one states 'contribute' the other 'be active'

https://github.com/foundersandcoders/oursite/pull/197/files#diff-b0e9bdf75d0c4dbda2734cbac51546eaR29

**Comment by sofer** [comment]
@Jbarget thank you. Updated.

**Comment by Jbarget** [comment]
@sofer could you update me with 'write' access so i can merge, thanks

**Comment by sofer** [comment]
@Jbarget done.

**Comment by Jbarget** [comment]
perfecto

**Pull request merged**
