### PR TITLE
Taking my name out of the candidates list, and updating my "status"

### PR DESCRIPTION
**Pull request by NataliaLKB**
Hey!

Just updating information about me in the fac3 blog, and taking my name out of the candidates page.

Cheers :beer:

### CODE REVIEW

**Comment by iteles** [comment]
:+1: Cheers Nat :blush:

**Comment by NataliaLKB** [comment]
Thanks @iteles !

**Comment by nelsonic** [comment]
Sad times (for FAC...) hope everything is going well for you Nat! :sparkles:

**Comment by NataliaLKB** [comment]
All is well! I miss you guys though. Will come visit when you are back :).

**Pull request merged**
