### PR TITLE
Create ux.md

### PR DESCRIPTION
**Pull request by sofer**
@izaakrogan 

I've created some copy for UX design.

I am thinking that the top line of our services should read: 

    UX design - Prototyping - Web application development 

and we can shift ```training``` to the second row , perhaps bumping ```responsive web design```.

### CODE REVIEW

**Comment by sofer** [comment]
...and we can reuse the ```responsive web design``` icon for ```UX design```

**Comment by iteles** [comment]
This is _not_ the place to discuss it, but I wanted it to be mentioned somewhere: if we're saying it's a service, I would **strongly recommend** we start teaching it. I would rather we not be part of propagating the myth that 'UX isn't real work' or 'UX is just drawing some pretty pictures' - our students actually need a little guidance on this stuff (and in the beginning, one of the more experienced devs from upstairs doing QA) :blush:

**Comment by sofer** [comment]
Agreed, but let that be a spur to our learning, rather than holding up publication. We still have plenty of scope to add to both the last two weeks of FAC5 and our prerequisites for FAC6.

**Comment by sofer** [comment]
We don't need this any more. I am going to delete the branch.

**Pull request closed without merging**
