### PR TITLE
added current version of logo

### PR DESCRIPTION
**Pull request by rub1e**

### CODE REVIEW

**Comment by iteles** [comment]
@rub1e Could you please assign your PRs to someone? :wink:

**Comment by rub1e** [comment]
sure - who's in charge of the website these days?

**Comment by iteles** [comment]
Good question for @sofer or the business meeting!

**Comment by rub1e** [comment]
cool, will raise this at the biz meeting on monday

in the meantime, is there someone who could review these as a matter of priority - it's more than a little concerning, given what we do as an organisation, that we've got visible markdown in the section where we showcase the quality of our work!!

**Comment by NataliaLKB** [comment]
Regarding the visible Markdown PRs, it would be much easier to review if they were all in one PR, not spread over several. Please combine into one, and feel free to assign myself (or someone else if you prefer).

**Pull request merged**
