### PR TITLE
new application guidelines

### PR DESCRIPTION
**Pull request by sofer**
You should be able to see the changes to the apply page here https://oursite-sofer.c9users.io/apply/.

Please merge and I will re-publish.

### CODE REVIEW

**Comment by sofer** [comment]
Fixes #259

**Comment by rebeccaradding** [comment]
@sofer, did I do that right? 

Also, do you want me to create a PDF with the additional recommended materials to add as a link at the bottom?

**Comment by rebeccaradding** [comment]
Also, there's a typo (my bad) in the first line. Should read: "Applications for our February cohorts **open** on..."

**Comment by rebeccaradding** [comment]
@sofer the version in the FAC Website outline Google doc is most current (sans typos) and includes this intro:

We don’t charge tuition because we believe that everyone should have access to high quality training in software development. 

Instead of money, we expect you to invest TIME in your development - specifically, 200+ hours of self-study before joining the programme (this amount may vary depending on your technical background).

**Pull request merged**
